### PR TITLE
Fix misc. trivial typos

### PR DESCRIPTION
**Pull request by luzpaz**
Found via `codespell -q 3 -S ./external,./IfcPlusPlus/src/external -L numer,wallthickness`

Please consider fixing the source typos for `segement`, `segements`, `appearence`, and `tesselator`

### CODE REVIEW

**Comment by ifcquery** [comment]
Thanks for the request.
If you agree, I can take over those changes. I can't merge pull requests though, because it could merge other licenses with it, which makes it too complicated.

**Comment by luzpaz** [comment]
Yea...i don't care about being associated with the commit. Just fixing typos :)

**Comment by luzpaz** [comment]
Rebased. Please take over

**Comment by ifcquery** [comment]
ok, fixed by latest upload. Thanks!

**Pull request closed without merging**
