### PR TITLE
fix bugs

### PR DESCRIPTION
**Pull request by shelltdf**
fix OSG debug link library
fix vc14 bugs

### CODE REVIEW

**Comment by ifcquery** [comment]
Why do you propose to check for _MSC_VER < 1900?
I have currently _MSC_VER 1911 and it works also without the proposed changes.

**Comment by shelltdf** [comment]
cbrt(x) and double round(double value) is already in math.h
I use visual studio community 2015 update 3

**Comment by ifcquery** [comment]
Could you also propose the changes in Carve in the official Carve repository? 
https://github.com/folded/carve
To be honest, I don't understand the complete Carve code.

**Comment by shelltdf** [comment]
ok i try it

**Comment by ifcquery** [comment]
Do you have compiler errors without the check  #if(_MSC_VER < 1900)?

**Comment by shelltdf** [comment]
just warning
duplicate definition

**Pull request merged**
