### PR TITLE
UTF-8 Making Korean files readable

### PR DESCRIPTION
**Pull request by wnsgml972**
This pull request contains the following changes:

* Reading Korean files using UTF-8 character encoding

### CODE REVIEW

**Comment by ifcquery** [comment]
Thanks for the patch. It will work only on windows though. Do you have a solution with just standard C++ so that it also runs on linux?

**Comment by wnsgml972** [comment]
Thank you very much for your reply.
I Switched to using standard C ++.

**Comment by ifcquery** [comment]
I added it manually, because I had some other changes to do. Thanks again for the solution!

**Comment by wnsgml972** [comment]
Thanks: D

**Pull request closed without merging**
